pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // [VPN test] Repli si tor-android n'est pas résolu sur Maven Central
        maven { url 'https://raw.githubusercontent.com/guardianproject/gpmaven/master' }
    }
}

rootProject.name = "PIPSIFLIX"
include ':app'
